program: main.o cliente.o comentario.o compra.o compraProducto.o controladorFecha.o controladorProducto.o controladorUsuario.o DT2Producto.o DTCliente.o DTComentario.o DTCompra.o DTCompraProducto.o DTFecha.o DTNotificacion.o DTProducto.o DTPromocion.o DTUsuario.o DTVendedor.o manejadorProducto.o manejadorUsuario.o producto.o productoPromocion.o promocion.o usuario.o vendedor.o
	g++ -o program main.o cliente.o comentario.o compra.o compraProducto.o controladorFecha.o controladorProducto.o controladorUsuario.o DT2Producto.o DTCliente.o DTComentario.o DTCompra.o DTCompraProducto.o DTFecha.o DTNotificacion.o DTProducto.o DTPromocion.o DTUsuario.o DTVendedor.o manejadorProducto.o manejadorUsuario.o producto.o productoPromocion.o promocion.o usuario.o vendedor.o

main.o: main.cpp
	g++ -c main.cpp

cliente.o: cliente.cpp
	g++ -c cliente.cpp

comentario.o: comentario.cpp
	g++ -c comentario.cpp

compra.o: compra.cpp
	g++ -c compra.cpp

compraProducto.o: compraProducto.cpp
	g++ -c compraProducto.cpp

controladorFecha.o: controladorFecha.cpp
	g++ -c controladorFecha.cpp

controladorProducto.o: controladorProducto.cpp
	g++ -c controladorProducto.cpp

controladorUsuario.o: controladorUsuario.cpp
	g++ -c controladorUsuario.cpp

DT2Producto.o: DT2Producto.cpp
	g++ -c DT2Producto.cpp

DTCliente.o: DTCliente.cpp
	g++ -c DTCliente.cpp

DTComentario.o: DTComentario.cpp
	g++ -c DTComentario.cpp

DTCompra.o: DTCompra.cpp
	g++ -c DTCompra.cpp

DTCompraProducto.o: DTCompraProducto.cpp
	g++ -c DTCompraProducto.cpp

DTFecha.o: DTFecha.cpp
	g++ -c DTFecha.cpp

DTNotificacion.o: DTNotificacion.cpp
	g++ -c DTNotificacion.cpp

DTProducto.o: DTProducto.cpp
	g++ -c DTProducto.cpp

DTPromocion.o: DTPromocion.cpp
	g++ -c DTPromocion.cpp

DTUsuario.o: DTUsuario.cpp
	g++ -c DTUsuario.cpp

DTVendedor.o: DTVendedor.cpp
	g++ -c DTVendedor.cpp

manejadorProducto.o: manejadorProducto.cpp
	g++ -c manejadorProducto.cpp

manejadorUsuario.o: manejadorUsuario.cpp
	g++ -c manejadorUsuario.cpp

producto.o: producto.cpp
	g++ -c producto.cpp

productoPromocion.o: productoPromocion.cpp
	g++ -c productoPromocion.cpp

promocion.o: promocion.cpp
	g++ -c promocion.cpp

usuario.o: usuario.cpp
	g++ -c usuario.cpp

vendedor.o: vendedor.cpp
	g++ -c vendedor.cpp

clean:
	rm -f *.o program