program: main.o cliente.o comentario.o compra.o compraProducto.o 
       controladorFecha.o controladorProducto.o controladorUsuario.o 
       DT2Producto.o DTCliente.o DTCompra.o DTCompraProducto.o 
       DTFecha.o DTNotificacion.o DTProducto.o DTPromocion.o 
       DTUsuario.o DTVendedor.o manejadorProducto.o manejadorUsuario.o 
       producto.o productoPromocion.o promocion.o usuario.o vendedor.o

main.0: main.cpp
	g++ -c main.cpp

cliente.0: cliente.cpp
	g++ -c cliente.cpp

comentario.0: comentario.cpp
	g++ -c comentario.cpp

compra.0: compra.cpp
	g++ -c compra.cpp
compraProducto.0: compraProducto.cpp
	g++ -c compraProducto.cpp



clean:
	rm -f *.o program